# -*- coding: utf-8 -*-
"""Swaponodaya

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11R1nea92JDCX9KXwi0awbAB8uOaxSexT

# Python program to convert upper case letters to lower case letters using ASKI values method
"""

a="Hello"
b=""
i=0
while i<len(a):
    if a[i]>="A" and a[i]<="Z":
        b=b+chr(ord(a[i])+32)
    i=i+1
print(b)

"""# Python program to convert upper case letters to lower case letters using ASKI values method with compine with lower case letters also

"""

a="Hello"
b=""
i=0
while i<len(a):
    if a[i]>="A" and a[i]<="Z":
        b=b+chr(ord(a[i])+32)
    else:
       b=b+a[i]
    i=i+1

print(b)

"""# input
####  a="kruthikk616@gmail.com
# output
#### b="kruthikkgmailcom"
#### c="123"
#### d="@."
#### by using the input email we should separate the email into character,number,special character

"""

a="kruthikk616@gmail.com"
b=""
c=""
d=""
i=0
while i<len(a):

    if (a[i]>="A" and a[i]<="Z") or(a[i]>="a" and a[i]<="z"):
        b=b+a[i]
    elif a[i] >="0" and a[i] <="9":
        c=c+a[i]
    else:
        d=d+a[i]
    i=i+1
print(b)
print(c)
print(d)

"""#input
a=[19,2,13,4,5,11,-1,-17]
#output
48
odd numbers=19,13,5,11
a=19+13+5+11=48
"""

a=[19,2,13,4,5,11,-1,-17]
b=0
i=0
while i<len(a):
    if a[i]>0 and a[i]%2==1:
        b=b+a[i]
    i=i+1
print(b)

"""#input
a="CSISESYSS"
#output
b="SSSS"

"""

a="CSISESYSS"
b=""
i=0
while i<len(a):
  if i%2==1:
    b=b+a[i]
  i=i+1
print(b)

"""## python program to print even numbers between 10-20"""

i=10
while i<=20:
  if  i%2==0:
      print(i)
  i=i+1

"""### 80-100 grade a ,

### 50-79 grade b,

### 35-49 grade c,

### below fail

"""

marks=int(input("enter the marks :"))
if marks>=0 and marks<=100:
    if marks>=80 and marks<=100:
       print("Grade A")
    elif marks>=50 and marks<=79:
       print("Grade B")
    elif marks>=35 and marks<=49:
        print("Grade C")
    else:
        print("Fail")
else:
    print("Invalid marks")

"""# Python program to validate user_id and password using nested if"""

uid=input("enter UID :")


if uid== "Kruthik1001":
    password=input("Enter password :")
    if password=="1234":
       print("Login Successfull")
    else:
       print("Password is Roung")
else:
  print("UID is roung")

"""# For loop"""

a="hello"
for i in a:
    print(i)

a="12345"
for i in a:
    print("12345")

"""#### print odd numbers between 6 and 12"""

for i in range(6,13):
    if i%2==0:
        print(i)

"""### input="teachers"
### output=48
"""

b="teachers"
d=0
for i in range(0,len(b)):
    if i%2==1:
        d=d+i
print(d)

"""### input="swapnodaya"
### output=sandy
"""

s="swapnodaya"
y=""
for i in range(len(s)):
    if i%2==0:
        y=y+s[i]
print(y)

b="Swapnodaya Exskilence"
c=0
i=0
while i<len(b):
    if b[i] in "aeiou":
        c=c+1
    i=i+1
print(c)

b="Swapnodaya Exskilence"
d=0
i=0
while i<len(b):
    if b[i] in ("aeiouAEIOU"):
        d=d+1
    i=i+1
print(c)

d=["hello",52,"hi"]
f=[]
for i in d:
    if type(i)==str:

        c=0
        for j in i:
            c=c+1
        f=f+[c]
print(f)

a="kruthik"
b=""
for i in a :
    b=i+b
print(b)

from re import I
a="kruthik"
b=""
for i in range(len(a),0,-1):
  print(a[i])

"""#### input="Malayalam"
#### output=a4
"""

b="Malayalam"
c=0
for i in b:
    if i=="a":
        c=c+1
print(f'a{c}')

b="Malayalam"
c=0
z="a"
for i in b:
  if i=="a":
    c=c+1
z=z+str(c)
print(z)

b="Malayalam"
c=0
z="a"
for i in b:
  if i=="a":
    c=c+1
print(z+str(c))

"""#### input="aabbccc"
#### output=a2b2c3
"""

z="aabbccc"
y=""
for i in z:
    if i not in y:
        c=0
        for j in z:

            if i==j:
                c=c+1
        y=y+i+str(c)
print(y)

"""# if ,else

"""

x=0
if not x:
  print("x is zero")
else:
  print("x is not zero")

x=5
if x>3:
  print("greater")
else:
  print("smaller")

x=7
if x%2==0:
  print("even")
elif x%2!=2:
  print("odd")
else:
  print("neither")

""" $5=under 12 or over 65
 $10 =between 12 and 65
  invalid age=below 0 and above 120
"""

age=78
if age <=0 or age>=120:
    print("Invalid age")
elif age<12 or age>65:
    print("$5")
else:
    print("$10")

"""### nested if condition

"""

x=4
y=6
if x+y==10:
  if x*y==24:
    print("sum is 10 and prodect is 24")
  else:
    print("sum is 10 and prodect is not 24")
else:
  print("sum is not10")

x=12
if x%3==0:
  if x%4==0:
    print("x divisible by 3 and x divisible by 4")
  else:
    print("x divisible by 3 and x not divisible by 4")
else:
  print("x not divisible by 3")

age=10
if age >=0 and age <=12:
    print("Child")
elif age >=13 and age <=19:
    print("Teenager")
elif age >=20 and age <=59:
    print("Adult")
elif age>60 and age<=120:
    print("Senior")
else:
    print("Error: Age must be between 0 and 120.")

year=0
if year>0:
    if (year%4==0) and (year%100!=0 or year%400==0):
        print("Leap year")
    else:
        print("Not a leap year")
else:
    print("Invalid year")

"""# errors

### syntex error
"""

z="aabbccc"
y=""
for i in z
    if i not in y:
        c=0
        for j in z:

            if i==j:
                c=c+1
        y=y+i+str(c)
print(y)

z="aabbccc
y=""
for i in z:
    if i not in y:
        c=0
        for j in z:

            if i==j:
                c=c+1
        y=y+i+str(c)
print(y)

"""## string index out of range

"""

b="Swapnodaya Exskilence"
d=0
i=0
while i<=len(b):
    if b[i] in ("aeiouAEIOU"):
        d=d+1
    i=i+1
print(c)

"""## name 'c' is not defined"""

b="Swapnodaya Exskilence"
#d=0
i=0
while i<len(b):
    if b[i] in ("aeiouAEIOU"):
        d=d+1
    i=i+1
print(c)

"""## type error

"""

b="Swapnodaya Exskilence"
d=0
i=0
while i<len[b]:
    if b[i] in ("aeiouAEIOU"):
        d=d+1
    i=i+1
print(c)

"""## logical erre"""

b="Swapnodaya Exskilence"
d=0
i=0
while i<len(b):
    if b[i] in ("aeiouAEIOU"):
        d=d+1
    i=+1
print(c)

for i in range(1,11):
  if i==6:
    continue
  print(i)

i=1
while i<=10:
  if i==6:
    i=i+1
    continue
  print(i)
  i=i+1

i=1
while i<=10:
  i=i+1
  if i==6:

    #i=i+1
    continue
  print(i)
  i=i+1

m=[23,76,89,97,4,67,23]
max=0
for i in m:
    if i>max:
        max=i
print(max)

m=[-3,-4,67,22,-23]
max=m[0]
for i in m:
    if i<max:
        max=i
print(max)

m=[23,76,89,97,4,67,23]
max=m[0]
for i in m:
    if i>max:
        max=i
print(max)

m=[-1,-2,0,]
for i in m:
    for j in m:
        if j>i:
            i=j
    break
print(i)

a=[34,78,56,98,99]
t1=a[0]
for i in a:
    if i>t1:
        t1=i
t2=a[0]
for j in a:

    if j>t2 and j<t1:
        t2=j
print(t2)

a=[4,98,99,89]
f=a[0]
s=a[0]
for i in a:
    if i>f:
        s=f
        f=i


    elif i>s:
        s=i
    elif i>s and i<f:
        s=i
print(s)

a=[4,98,99,89]
f=a[0]
s=a[0]
for i in a:
    if i>f:
       s,f=f,i
    elif i>s:
        s=i
    elif i>s and i<f:
        s=i
print(s)

"""# continue

"""

numbers=[10,20,30,40,50]
i=0
while i<len(numbers):
    i=i+1
    if numbers[i-1]==30:
        continue
    print(numbers[i-1])

n=[1,2,3,4,5,6]
for i in n:
    if i%3==0:
        continue
    print(i, end=" ")

for i in range(1,6):
    if i%2==0:
        continue
    print(i,end=" ")

def sum_of_positive_numbers(numbers):
    # WRITE YOUR CODE HERE...
    sum=0
    if (len(numbers)<1 or len(numbers)>100):

        print("Input list does not meet the constraints")
    else:
        for i in numbers:
            if i>1000 or i<-1000:
                print("Input list does not meet the constraints")
            if i<0:
                continue
            sum+=i
        print("Sum of positive numbers:",sum)



numbers = [10, -5, 3, -1, 7, -2]
print(sum_of_positive_numbers(numbers))

"""# break"""

i=1
while i<10:
    if i%3==0:
        break
    i=i+1
print(i)

a=["red","pink","blue","green"]
i=0
while i<len(a):
    if len(a[i])>4:

        break

    print(a[i],end=" ")
    i=i+1

i=0
while i<8:
    print(i,end="")
    i=i+1
    if i ==6:
        break

def process_words(words):
    # WRITE YOUR CODE HERE
    if len(words)<1 or len(words)>100:
        print("Error: The list must contain between 1 and 100 words")
    else:
        for i in words:
            if i=="":
                break
            print(i,end=" ")

words = ["apple", "banana", "cherry"]
process_words(words)

def calculate_sum(numbers_list):
    # WRITE YOUR CODE HERE...
    total_sum = 0

    for number in numbers_list:
       if number < 0:
          break
       total_sum += number
    print("Total sum of positive numbers:",total_sum )

numbers_list = [7, 3, 0, 8, -2, 4]
calculate_sum(numbers_list)

def fact(u):

  r=1
  for i in range(1,u+1):
    r=r*i
  return r
print(fact(5))

def add(a,b,c):
    return a+b+c
print(add(1,2,3))